version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - npm
    groups:
      production-deps:
        dependency-type: production
      development-deps:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: staging
    labels:
      - dependencies
      - github-actions
