/**
 * Full-bleed marquee of illustrated tiles under the hero (public/art, generated by
 * scripts/generate-brand-art.ts). Pure CSS: the track holds two copies of the list
 * and slides by half its width; it pauses on hover and is static under
 * prefers-reduced-motion.
 */

const TILES = [
  { file: 'git-push', alt: 'Git push launching a deployment' },
  { file: 'server-rack', alt: 'Server rack with status lights' },
  { file: 'database-backup', alt: 'Database with scheduled backups to object storage' },
  { file: 'tls-shield', alt: 'Shield and padlock for automatic HTTPS' },
  { file: 'terminal', alt: 'Terminal window with a blinking cursor' },
  { file: 'team', alt: 'Team avatars with a key for role-based access' },
  { file: 'domains', alt: 'Globe with routes to several custom domains' },
  { file: 'compose-blocks', alt: 'Stacked containers snapping together like building blocks' },
] as const;

function Marker({ className }: { className: string }) {
  return <span className={`absolute size-2 bg-foreground ${className}`} aria-hidden />;
}

export function ArtStrip() {
  const row = [...TILES, ...TILES];
  return (
    <section className="relative border-y border-foreground/80 py-4" aria-label="What Peon handles for you">
      <Marker className="-top-1 left-6" />
      <Marker className="-top-1 right-6" />
      <Marker className="-bottom-1 left-6" />
      <Marker className="-bottom-1 right-6" />
      <div className="overflow-hidden">
        <ul className="animate-marquee flex w-max gap-4 hover:[animation-play-state:paused]">
          {row.map((t, i) => (
            <li key={`${t.file}-${i}`} className="shrink-0" aria-hidden={i >= TILES.length}>
              {/* eslint-disable-next-line @next/next/no-img-element -- static, pre-sized art tiles */}
              <img
                src={`/art/${t.file}.webp`}
                alt={i < TILES.length ? t.alt : ''}
                width={1536}
                height={1024}
                loading={i < 3 ? 'eager' : 'lazy'}
                decoding="async"
                className="h-44 w-auto rounded-sm sm:h-56"
              />
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
